export interface ExtraThemeBank {
  readonly id: string;
  readonly title: string;
  readonly words: readonly string[];
}

const bank = (id: string, title: string, words: string): ExtraThemeBank => ({
  id,
  title,
  words: Object.freeze(words.trim().split(/\s+/u)),
});

export const EXTRA_THEME_BANKS: readonly ExtraThemeBank[] = Object.freeze([
  bank("dogs", "Dogs", "beagle collie poodle boxer mastiff terrier spaniel retriever bulldog husky corgi dalmatian shepherd doberman pointer setter whippet akita saluki schnauzer"),
  bank("cats", "Cats", "siamese persian bengal sphynx ragdoll burmese savannah manx birman angora rex tabby calico tuxedo kitten whisker pounce scratch meow feline"),
  bank("horses", "Horses", "stallion mare foal pony mustang arabian appaloosa palomino chestnut sorrel canter gallop trot saddle bridle stirrup stable pasture jockey hoof"),
  bank("farm", "Farm", "tractor barn silo pasture harvest plough farmer cattle sheep goat pig chicken rooster donkey horse haystack orchard fence field dairy"),
  bank("zoo", "Zoo", "keeper habitat enclosure safari aviary reptile penguin panda zebra giraffe elephant gorilla tiger lion otter seal monkey camel koala"),
  bank("canines", "Canines", "wolf fox coyote jackal dingo dhole dog pup vixen den pack howl muzzle paw tail fur hunter scent canine tundra"),
  bank("felines", "Felines", "lion tiger leopard jaguar cheetah cougar lynx ocelot caracal serval bobcat panther kitten whisker claw pounce prowl pride feline"),
  bank("primates", "Primates", "gorilla chimp bonobo orangutan gibbon baboon macaque lemur loris marmoset tamarin monkey langur mandrill howler capuchin troop canopy jungle"),
  bank("rodents", "Rodents", "mouse rat hamster gerbil beaver squirrel marmot vole lemming capybara chinchilla porcupine dormouse muskrat gopher burrow gnaw whisker tail"),
  bank("raptors", "Raptors", "eagle hawk falcon osprey kestrel harrier buzzard kite condor vulture talon beak soar glide perch prey nest wing feather hunter"),
  bank("songbirds", "Songbirds", "robin thrush finch canary sparrow warbler wren lark bunting oriole blackbird starling nightingale swallow martin song nest chorus feather"),
  bank("waterbirds", "Waterbirds", "duck goose swan heron egret crane stork pelican cormorant grebe loon gull tern puffin flamingo ibis bittern marsh wader"),
  bank("poultry", "Poultry", "chicken rooster hen chick turkey duck goose quail pheasant guinea bantam broiler pullet coop hatch egg feather beak flock grain"),
  bank("butterflies", "Butterflies", "monarch swallowtail painted admiral skipper sulphur copper blue fritillary morpho wing antenna nectar pollen cocoon chrysalis garden meadow flutter"),
  bank("beetles", "Beetles", "ladybug scarab weevil stag click jewel ground dung blister longhorn chafer firefly grub shell antenna mandible wing garden forest crawl"),
  bank("spiders", "Spiders", "tarantula widow recluse orbweaver huntsman wolf cellar funnel jumping crab web silk fang venom eightleg prey spinner cave garden"),
  bank("bees", "Bees", "honeybee bumble mason miner carpenter queen drone worker hive comb wax honey nectar pollen swarm sting flower meadow keeper"),
  bank("ants", "Ants", "worker queen soldier colony nest tunnel mound larva pupa mandible antenna trail forage swarm leafcutter fire harvester carpenter sugar"),
  bank("mollusks", "Mollusks", "snail slug clam oyster mussel scallop octopus squid cuttlefish nautilus limpet conch whelk abalone shell mantle tentacle ink reef"),
  bank("crustaceans", "Crustaceans", "crab lobster shrimp prawn crayfish barnacle krill isopod copepod hermit claw shell antenna molt reef tidepool ocean seabed"),
  bank("fish", "Fish", "salmon trout tuna cod bass carp perch pike herring sardine anchovy mackerel marlin swordfish catfish eel guppy snapper fin gill"),
  bank("sharks", "Sharks", "greatwhite hammerhead tiger mako nurse whale reef lemon bull thresher goblin sawshark angel dogfish fin gill tooth predator ocean"),
  bank("whales", "Whales", "blue humpback sperm orca beluga narwhal bowhead right gray minke sei fin whale calf pod baleen blowhole fluke breach ocean"),
  bank("dolphins", "Dolphins", "bottlenose spinner spotted dusky river common striped hector risso pilot pod calf click whistle sonar fin fluke leap ocean playful"),
  bank("amphibians", "Amphibians", "frog toad newt salamander axolotl caecilian tadpole spawn pond marsh gill skin croak leap damp change habitat insect"),
  bank("snakes", "Snakes", "cobra python viper boa mamba adder krait anaconda rattler taipan coral racer kingsnake hognose fang venom scale coil slither tongue"),
  bank("turtles", "Turtles", "tortoise terrapin loggerhead leatherback hawksbill green box snapping painted shell flipper hatchling beach pond bask crawl reef ocean"),
  bank("lizards", "Lizards", "gecko iguana skink monitor anole agama chameleon basilisk dragon gila whiptail horned scale tail claw bask desert forest insect"),
  bank("nocturnal", "Nocturnal", "owl bat moth badger raccoon fox hedgehog possum civet hyena firefly cricket moon shadow dusk night burrow hunt silent star"),
  bank("migration", "Migration", "journey flock herd school route season compass instinct north south passage stopover feeding breeding salmon monarch swallow caribou whale"),
  bank("habitats", "Habitats", "forest desert ocean tundra grassland wetland jungle river lake reef cave mountain meadow coast swamp prairie canopy burrow nest"),
  bank("endangered", "Endangered", "panda tiger rhino gorilla orangutan elephant leopard turtle condor whale dolphin pangolin tapir saola habitat poaching rescue refuge protect"),
  bank("conservation", "Conservation", "protect restore habitat species refuge reserve ranger recycle climate forest ocean wildlife nature balance ecology rescue monitor preserve future"),
  bank("ecosystems", "Ecosystems", "producer consumer predator prey habitat climate soil water sunlight nutrient energy foodweb balance species niche biome decay growth cycle"),
  bank("rainforest", "Rainforest", "canopy jungle vine orchid fern toucan jaguar monkey parrot humid rainfall river moss bamboo cocoa kapok liana insect emerald tropical"),
  bank("wetlands", "Wetlands", "marsh swamp bog fen reed rush heron frog turtle beaver otter lily mud waterfowl peat mangrove estuary flood pond sedge"),
  bank("grasslands", "Grasslands", "prairie steppe pampas veld savanna grass bison antelope zebra lion hyena burrow wildflower herd wind plain horizon fire drought"),
  bank("taiga", "Taiga", "spruce pine fir larch moss snow wolf moose bear lynx owl hare cold forest bog cabin winter cone evergreen north wilderness"),
  bank("savanna", "Savanna", "acacia grass zebra giraffe lion cheetah elephant rhino gazelle hyena vulture termite drought rainfall herd plain watering safari sunset"),
  bank("volcanoes", "Volcanoes", "lava magma crater vent ash plume cone caldera basalt eruption dormant active summit tremor island smoke molten rock flow geology"),
  bank("caves", "Caves", "cavern tunnel chamber stalactite stalagmite crystal bat echo darkness limestone grotto sinkhole drip pool passage torch explorer underground rock"),
  bank("lakes", "Lakes", "superior victoria baikal tahoe geneva como titicaca erie huron michigan ontario ladoga balkhash shore island water canoe fishing ripple"),
  bank("beaches", "Beaches", "sand dune shell wave tide surf coast shore cove bay palm towel umbrella bucket castle driftwood sunset breeze gull coral"),
  bank("reefs", "Reefs", "coral atoll lagoon anemone sponge urchin starfish parrotfish clownfish turtle shark ray polyp algae reef ocean snorkel diver current"),
  bank("glaciers", "Glaciers", "ice snow crevasse moraine serac melt frozen valley alpine polar calving iceberg frost blue ancient flow climate expedition ridge"),
  bank("waterfalls", "Waterfalls", "cascade plunge mist spray river cliff gorge pool rainbow torrent rapids drop ledge roar foam valley forest erosion scenic"),
  bank("canyons", "Canyons", "gorge ravine cliff mesa plateau river sandstone granite erosion rim trail depth valley rock desert echo lookout strata winding"),
  bank("meadows", "Meadows", "grass clover daisy buttercup poppy bee butterfly lark breeze brook pasture bloom sunlight dew hay rabbit fox wildflower green"),
  bank("seasons", "Seasons", "spring summer autumn winter solstice equinox thaw bloom harvest frost sunlight rainfall snowfall breeze change cycle warmth cold daylight"),
  bank("spring", "Spring", "blossom tulip daffodil robin nest rain shower rainbow bud sprout meadow lamb butterfly breeze thaw green garden pollen sunshine"),
  bank("summer", "Summer", "sunshine beach picnic holiday swimming surfing camping lemonade sandal garden sunset warm thunder firefly hammock barbecue ocean travel"),
  bank("autumn", "Autumn", "harvest pumpkin acorn chestnut maple amber orange leaf crisp orchard cider haystack sweater mist bonfire equinox breeze woodland"),
  bank("winter", "Winter", "snow frost ice blizzard mitten scarf sled ski skate cocoa fireplace evergreen icicle snowman cold frozen cabin blanket crystal"),
  bank("storms", "Storms", "thunder lightning tornado cyclone hurricane monsoon blizzard hail downpour gust cloud radar warning shelter surge flood wind rain"),
  bank("clouds", "Clouds", "cirrus cumulus stratus nimbus alto wispy fluffy overcast vapor sky storm rain silver white drift layer forecast horizon"),
  bank("winds", "Winds", "breeze gust gale squall monsoon trade mistral sirocco zephyr cyclone draft current air vane sail turbine storm whisper"),
  bank("rain", "Rain", "drizzle shower downpour monsoon cloud puddle droplet umbrella rainbow storm mist damp splash gutter forecast garden roofcoat thunder"),
  bank("snow", "Snow", "flake drift powder blizzard frost sleet crystal snowman snowball igloo sled ski mitten white cold winter frozen plough avalanche"),
  bank("minerals", "Minerals", "quartz feldspar mica calcite gypsum talc halite fluorite apatite topaz corundum magnetite hematite pyrite sulfur graphite crystal ore"),
  bank("crystals", "Crystals", "quartz amethyst citrine geode prism lattice facet cluster clear sparkle mineral growth cave point shard violet rose smoky"),
  bank("gemstones", "Gemstones", "diamond ruby sapphire emerald opal topaz garnet amethyst jade pearl onyx quartz turquoise zircon spinel peridot jewel facet"),
  bank("trees", "Trees", "oak maple pine cedar birch willow elm ash beech fir spruce redwood sequoia chestnut poplar cypress acacia baobab trunk leaf"),
  bank("herbs", "Herbs", "basil thyme mint sage dill parsley chive oregano rosemary cilantro tarragon fennel marjoram lavender chamomile sorrel leaf garden aroma"),
  bank("spices", "Spices", "pepper cumin paprika turmeric saffron ginger cinnamon nutmeg clove cardamom anise sumac coriander mustard vanilla chili aroma grind"),
  bank("seeds", "Seeds", "sesame poppy sunflower pumpkin flax chia hemp mustard cumin fennel melon apple grape kernel sprout shell sow harvest garden"),
  bank("berries", "Berries", "strawberry blueberry raspberry blackberry cranberry gooseberry mulberry elderberry currant boysenberry cloudberry berry sweet tart bush jam pie"),
  bank("citrus", "Citrus", "orange lemon lime grapefruit mandarin tangerine pomelo kumquat citron clementine yuzu bergamot peel zest juice grove sour fresh"),
  bank("orchards", "Orchards", "apple pear peach plum cherry apricot quince fig olive almond walnut blossom branch ladder basket harvest farmer cider grove"),
  bank("farming", "Farming", "plough tractor seed crop field soil farmer barn harvest wheat corn rice barley oat irrigation pasture fence dairy orchard"),
  bank("harvest", "Harvest", "wheat corn barley oat rice apple grape pumpkin basket sickle combine farmer field crop grain orchard autumn bounty store"),
  bank("botany", "Botany", "root stem leaf flower seed pollen petal fruit bark branch bud cell sap xylem phloem species flora growth soil"),
  bank("ecology", "Ecology", "habitat species niche biome foodweb predator prey energy climate population balance nature field study sample forest water soil"),
  bank("wildlife", "Wildlife", "animal habitat forest ranger reserve tracks camera binoculars herd flock den nest paw hoof claw feather fur wild protect observe"),
  bank("succulents", "Succulents", "aloe agave echeveria sedum jade cactus haworthia kalanchoe rosette spine fleshy drought pot soil sunlight desert bloom water"),
  bank("mushrooms", "Mushrooms", "morel truffle porcini chanterelle oyster shiitake button enoki maitake cap stem gill spore mycelium forest damp basket edible"),
  bank("ferns", "Ferns", "bracken maidenhair sword royal ostrich tree frond fiddlehead spore rhizome shade damp forest green unfurl moss garden ancient"),
  bank("bamboo", "Bamboo", "culm shoot grove panda grass hollow node leaf green rapid garden forest flute basket screen strong tall tropical"),
  bank("cactus", "Cactus", "saguaro barrel prickly cholla organpipe peyote spine desert bloom flower pad drought arid sand succulent green tall water"),
  bank("bread", "Bread", "baguette sourdough brioche ciabatta focaccia rye wheat pita naan bagel pretzel loaf crust crumb yeast dough oven toast baker"),
  bank("cheese", "Cheese", "cheddar brie gouda swiss feta edam stilton manchego ricotta parmesan mozzarella camembert provolone curd whey dairy rind slice"),
  bank("pasta", "Pasta", "spaghetti penne fusilli ravioli lasagna linguine rigatoni farfalle orzo gnocchi macaroni tortellini noodle sauce basil cheese boil"),
  bank("pizza", "Pizza", "margherita pepperoni mushroom olive tomato cheese basil crust dough oven slice topping sauce garlic onion pepper ham mozzarella"),
  bank("soups", "Soups", "broth bisque chowder minestrone gazpacho lentil tomato onion chicken noodle pumpkin mushroom miso ramen stock bowl spoon simmer"),
  bank("salads", "Salads", "lettuce tomato cucumber onion pepper carrot olive spinach rocket cabbage beet radish avocado dressing bowl fresh crisp toss"),
  bank("sandwiches", "Sandwiches", "bread cheese ham turkey tuna chicken bacon tomato lettuce pickle mustard mayo toast roll wrap club panini filling"),
  bank("breakfast", "Breakfast", "toast cereal oatmeal pancake waffle bacon egg sausage yogurt fruit coffee tea muffin croissant jam honey bowl plate morning"),
  bank("pastries", "Pastries", "croissant danish eclair strudel turnover tart scone muffin donut macaron cannoli baklava choux dough butter cream sugar oven"),
  bank("chocolate", "Chocolate", "cocoa cacao truffle praline fudge brownie ganache dark milk white bar chip syrup sweet bitter melt wrapper bean"),
  bank("candy", "Candy", "caramel toffee nougat gummy lollipop bonbon mint jellybean liquorice marshmallow taffy sugar sweet wrapper chew sour hard soft"),
  bank("icecream", "Icecream", "vanilla chocolate strawberry pistachio caramel mango coconut mint gelato sorbet cone scoop sundae wafer sprinkle freezer creamy"),
  bank("cakes", "Cakes", "sponge carrot velvet chiffon fruitcake cupcake cheesecake brownie lemon marble coffee layer icing candle slice bake party"),
  bank("cookies", "Cookies", "biscuit wafer ginger snap oatmeal butter shortbread macaron fortune sandwich chocchip dough crumb bake tray jar sweet crunchy"),
  bank("nuts", "Nuts", "almond walnut cashew peanut pecan pistachio hazelnut macadamia chestnut brazil acorn kernel shell roast salted crunchy snack"),
  bank("grains", "Grains", "wheat rice barley oat rye millet quinoa corn spelt buckwheat sorghum farro bran kernel flour cereal harvest field"),
  bank("seafood", "Seafood", "salmon tuna cod shrimp prawn lobster crab oyster mussel clam scallop squid octopus anchovy sardine fillet shell grill"),
  bank("sushi", "Sushi", "nigiri maki sashimi temaki uramaki salmon tuna shrimp eel rice nori wasabi ginger soy roll chef chopstick"),
  bank("barbecue", "Barbecue", "grill smoke brisket rib chicken sausage steak skewer charcoal flame sauce rub tongs apron picnic corn pepper backyard"),
  bank("snacks", "Snacks", "chips popcorn cracker pretzel nuts fruit cookie granola yogurt candy toast dip salsa hummus cheese wafer bar crunchy"),
  bank("drinks", "Drinks", "water juice tea coffee cocoa milk soda lemonade smoothie shake cider tonic cola punch nectar bottle glass straw ice"),
  bank("tea", "Tea", "earlgrey sencha matcha oolong jasmine assam darjeeling rooibos chai mint chamomile kettle cup leaf steep aroma honey lemon"),
  bank("juices", "Juices", "orange apple grape mango tomato carrot berry lemon lime pineapple peach pear melon cherry pulp fresh press glass vitamin"),
  bank("tropical", "Tropical", "mango papaya guava coconut pineapple banana lychee passionfruit dragonfruit starfruit kiwi lime sweet juicy island market"),
  bank("condiments", "Condiments", "ketchup mustard mayo relish vinegar soy salsa pesto chutney wasabi horseradish hot sauce pickle dip bottle flavor"),
  bank("baking", "Baking", "flour sugar butter egg yeast dough batter whisk bowl oven tray loaf cake cookie pastry knead rise measure recipe"),
  bank("cooking", "Cooking", "boil fry roast bake grill steam simmer saute chop slice dice stir mix season taste pan pot chef recipe"),
  bank("dairy", "Dairy", "milk cream butter cheese yogurt whey curd custard kefir gelato cow goat farm churn bottle carton fresh calcium"),
  bank("vineyard", "Vineyard", "grape vine cluster leaf harvest barrel cellar cork bottle press grower valley slope soil sun tasting vintage orchard"),
  bank("market", "Market", "stall vendor basket produce fruit vegetable bread cheese spice flower fish butcher baker shopper coin price fresh local"),
  bank("continents", "Continents", "africa europe asia america oceania antarctica eurasia north south east west equator globe landmass ocean map border hemisphere"),
  bank("europe", "Europe", "france spain italy germany greece poland norway sweden finland ireland austria belgium croatia serbia albania estonia latvia lithuania"),
  bank("asia", "Asia", "china japan india korea thailand vietnam cambodia nepal bhutan mongolia malaysia indonesia singapore pakistan laos myanmar bangladesh maldives"),
  bank("africa", "Africa", "kenya egypt ghana senegal morocco tunisia angola namibia zambia uganda rwanda ethiopia somalia sudan nigeria botswana malawi lesotho"),
  bank("americas", "Americas", "canada mexico brazil chile peru bolivia panama cuba haiti belize guyana suriname uruguay paraguay ecuador colombia argentina jamaica"),
  bank("oceania", "Oceania", "australia zealand fiji samoa tonga vanuatu kiribati nauru palau tuvalu guam tahiti papua solomon micronesia melanesia polynesia"),
  bank("nordics", "Nordics", "denmark norway sweden finland iceland greenland faroe copenhagen oslo stockholm helsinki reykjavik fjord sauna aurora viking tundra"),
  bank("balkans", "Balkans", "albania bosnia bulgaria croatia greece kosovo serbia slovenia romania macedonia tirana sarajevo sofia zagreb belgrade skopje adriatic"),
  bank("alps", "Alps", "montblanc matterhorn eiger jungfrau dolomite glacier summit chalet meadow valley ridge pass cablecar climber snow ski austria swiss italy"),
  bank("andes", "Andes", "aconcagua alpaca condor llama peru chile bolivia ecuador colombia volcano plateau glacier summit valley puna inca quechua altitude range"),
  bank("himalayas", "Himalayas", "everest kangechen lhotse makalu chooyu dhaula manaslu annapurna nepal tibet bhutan sherpa yak summit glacier monastery prayer altitude"),
  bank("rockies", "Rockies", "denali elbert robson glacier banff jasper aspen boulder valley canyon ridge summit forest elk bear trail lodge snow alpine"),
  bank("caribbean", "Caribbean", "cuba jamaica haiti bahamas barbados aruba curacao grenada dominica antigua tobago martinique cayman belize island coral beach salsa"),
  bank("pacific", "Pacific", "fiji tahiti hawaii guam samoa tonga palau midway wake nauru tuvalu kiribati coral atoll lagoon volcano island wave ocean"),
  bank("atlantic", "Atlantic", "azores bermuda canary madeira iceland ireland britain bahamas capeverde current gulfstream ocean voyage island storm whale coast deep"),
  bank("baltic", "Baltic", "sweden finland estonia latvia lithuania poland germany denmark gotland riga tallinn helsinki gdansk ferry amber coast island sea"),
  bank("sahara", "Sahara", "dune oasis camel nomad caravan mirage sand desert sun heat wind scorpion cactus tent atlas tuareg salt dry horizon"),
  bank("amazonia", "Amazonia", "amazon jungle river brazil peru canopy jaguar toucan anaconda piranha orchid kapok tribe canoe rainfall humid green tributary wildlife"),
  bank("patagonia", "Patagonia", "argentina chile andes glacier puma guanaco condor steppe fjord wind lake peak trek sheep coast penguin wilderness south"),
  bank("siberia", "Siberia", "taiga tundra russia baikal yakutsk irkutsk snow frost birch pine wolf tiger sable reindeer railway exile vast cold east"),
  bank("scotland", "Scotland", "edinburgh glasgow aberdeen dundee highland lowland hebrides orkney skye loch ness thistle tartan castle whisky bagpipe glen"),
  bank("ireland", "Ireland", "dublin cork galway limerick belfast ulster leinster munster connacht shamrock clover harp castle coast emerald pub dance gaelic"),
  bank("france", "France", "paris lyon nice bordeaux toulouse dijon nantes normandy brittany provence alps loire seine louvre baguette cheese beret cafe"),
  bank("italy", "Italy", "rome milan venice florence naples turin genoa verona sicily sardinia tuscany alps po tiber colosseum pasta pizza opera"),
  bank("spain", "Spain", "madrid barcelona seville valencia bilbao granada malaga toledo ibiza canary andalusia catalonia pyrenees tapas flamenco paella fiesta"),
  bank("portugal", "Portugal", "lisbon porto braga coimbra algarve madeira azores douro tagus fado cork tile sardine custard castle atlantic voyage"),
  bank("germany", "Germany", "berlin munich hamburg cologne frankfurt dresden leipzig bremen bavaria saxony rhine danube alps forest castle pretzel autobahn"),
  bank("greece", "Greece", "athens sparta delphi crete rhodes corfu mykonos santorini olympus aegean ionian acropolis temple olive feta marble island myth"),
  bank("egypt", "Egypt", "cairo luxor giza aswan nile delta pyramid sphinx pharaoh temple tomb desert papyrus mummy scarab oasis alexandria hieroglyph"),
  bank("morocco", "Morocco", "rabat marrakesh casablanca fez tangier atlas sahara medina souk riad tajine mint mosaic desert coast camel spice carpet"),
  bank("kenya", "Kenya", "nairobi mombasa nakuru savanna safari lion elephant giraffe zebra flamingo masai mara kilimanjaro tea coffee coast lake valley"),
  bank("japan", "Japan", "tokyo kyoto osaka nara hokkaido fuji sakura sushi ramen kimono samurai shogun shrine temple bamboo anime manga island"),
  bank("china", "China", "beijing shanghai shenzhen guangzhou wuhan tibet hainan yangtze yellow wall panda dragon silk tea rice pagoda lantern"),
  bank("india", "India", "delhi mumbai kolkata chennai jaipur agra goa kerala punjab bengal ganges tajmahal curry sari yoga monsoon tiger"),
  bank("brazil", "Brazil", "brasilia rio sao paulo bahia amazon parana iguazu samba carnival coffee football toucan jaguar beach rainforest capoeira"),
  bank("mexico", "Mexico", "capital cancun oaxaca puebla tijuana yucatan mayan aztec taco salsa mariachi cactus cenote desert pacific caribbean fiesta"),
  bank("canada", "Canada", "ottawa toronto montreal vancouver calgary quebec yukon alberta ontario manitoba maple moose beaver hockey tundra aurora"),
  bank("australia", "Australia", "sydney melbourne perth darwin adelaide tasmania outback reef koala kangaroo wombat dingo platypus eucalyptus desert surf"),
  bank("states", "States", "alabama alaska arizona arkansas california colorado delaware florida georgia hawaii idaho indiana iowa kansas kentucky maine montana nevada"),
  bank("london", "London", "thames westminster chelsea camden greenwich soho brixton paddington tower bridge palace parliament museum underground taxi"),
  bank("paris", "Paris", "eiffel louvre seine montmartre bastille sorbonne versailles opera metro cafe boulevard bridge garden museum notre dame"),
  bank("tokyo", "Tokyo", "shibuya shinjuku ginza asakusa ueno akihabara harajuku roppongi sumida metro tower shrine sushi neon crossing"),
  bank("rome", "Rome", "colosseum vatican pantheon forum trevi capitoline tiber piazza basilica ruins statue fountain gelato pasta empire"),
  bank("islandlife", "Islandlife", "lagoon palm beach coral canoe coconut volcano village fishing sunset breeze hammock shell reef tide sand boat"),
  bank("peninsulas", "Peninsulas", "arabia iberia korea india italy florida alaska yucatan sinai balkan jutland malay kamchatka anatolia coast cape gulf"),
  bank("deltas", "Deltas", "nile mekong ganges danube rhine mississippi niger indus orinoco volga sediment marsh channel estuary fertile river fan flood"),
  bank("fjords", "Fjords", "norway iceland greenland inlet cliff glacier waterfall village ferry mountain deep coast seal eagle kayak mist blue"),
  bank("archipelago", "Archipelago", "island chain atoll reef ocean ferry volcano lagoon coast channel strait palm beach fishing harbor sail remote tropical"),
  bank("maps", "Maps", "atlas compass legend scale border route symbol contour grid latitude longitude north south east west globe chart paper"),
  bank("navigation", "Navigation", "compass map route bearing north south east west landmark chart radar sonar beacon signal course pilot sailor gps"),
  bank("roadtrip", "Roadtrip", "car highway motel map luggage camera snack music fuel compass route bridge tunnel mountain coast desert city adventure"),
  bank("camping", "Camping", "tent sleepingbag lantern torch stove kettle compass map backpack trail boots campfire marshmallow forest lake rope peg"),
  bank("hiking", "Hiking", "trail boots backpack compass map summit valley forest ridge creek pole jacket water snack climb trek view nature"),
  bank("backpacking", "Backpacking", "hostel passport ticket train bus map backpack budget journey city border camera guide market laundry freedom"),
  bank("airports", "Airports", "runway terminal gate lounge baggage passport customs pilot cabin tower radar ticket boarding arrival departure shuttle"),
  bank("hotels", "Hotels", "lobby suite room key reception concierge porter luggage elevator breakfast pool spa balcony booking guest pillow"),
  bank("museums", "Museums", "gallery exhibit artifact curator painting sculpture history science ticket guide hall display archive visitor culture"),
  bank("castles", "Castles", "tower moat keep wall gate bridge dungeon throne knight banner courtyard stone fortress palace guard crown siege"),
  bank("bridges", "Bridges", "arch beam cable truss span tower deck pier river steel stone crossing suspension railway road engineer"),
  bank("towers", "Towers", "eiffel pisa tokyo cn burj shard sears spire antenna lookout clock bell stone steel skyline height elevator"),
  bank("monuments", "Monuments", "statue arch obelisk memorial column temple tomb tower shrine pyramid stone plaque history hero square landmark"),
  bank("ruins", "Ruins", "pompeii petra angkor machu troy delphi teotihuacan palmyra carthage temple column stone ancient dig artifact wall"),
  bank("archaeology", "Archaeology", "excavate artifact pottery fossil ruin tomb temple coin tool bone shard trench brush site ancient museum date"),
  bank("empires", "Empires", "roman ottoman mongol persian byzantine aztec inca mughal british spanish french austrian russian chinese colony emperor"),
  bank("romeempire", "Romans", "caesar augustus nero hadrian trajan senate legion consul forum aqueduct colosseum road toga latin eagle empire"),
  bank("egyptians", "Egyptians", "pharaoh pyramid sphinx nile mummy papyrus scarab temple tomb anubis osiris isis ra hieroglyph gold desert"),
  bank("vikings", "Vikings", "longship raider shield axe helmet fjord norse rune saga thor odin freya village voyage warrior sail north"),
  bank("samurai", "Samurai", "katana armor shogun daimyo ronin dojo honor clan bow horse castle japan warrior duel banner zen code"),
  bank("knights", "Knights", "armor sword shield lance horse castle squire joust helmet banner king queen quest dragon battle honor"),
  bank("pirates", "Pirates", "captain ship sail treasure island parrot map compass cannon cutlass crew deck anchor flag chest gold ocean"),
  bank("renaissance", "Renaissance", "florence venice artist painter sculptor humanism science anatomy printing patron fresco dome marble studio invention"),
  bank("revolution", "Revolution", "liberty freedom protest citizen republic banner march reform change rights leader crowd speech vote history"),
  bank("medieval", "Medieval", "castle knight peasant monk abbey market guild crown sword village plague harvest feast herald stone"),
  bank("ancient", "Ancient", "egypt rome greece persia china india temple palace king script pottery bronze iron trade myth army"),
  bank("stoneage", "Stoneage", "cave flint spear fire hunter gatherer mammoth bison hide tribe tool stone camp art bone survival"),
  bank("bronzeage", "Bronzeage", "bronze copper tin forge sword shield chariot city trade palace king temple pottery script farmer"),
  bank("silkroad", "Silkroad", "silk spice caravan camel oasis desert china persia india market trader route mountain coin tea jade"),
  bank("exploration", "Discovery", "voyage ship compass map sailor captain ocean island coast route expedition journal telescope harbor world"),
  bank("folklore", "Folklore", "legend tale hero giant witch fairy troll goblin spirit forest village magic song story monster"),
  bank("fairytales", "Fairytales", "princess prince castle dragon fairy witch giant dwarf forest mirror slipper pumpkin wolf tower magic"),
  bank("legends", "Legends", "arthur merlin robin beowulf atlantis eldorago excalibur grail hero quest sword crown myth tale bard"),
  bank("dragons", "Dragons", "fire scale wing claw fang cave treasure knight castle smoke flight tail horn legend egg beast"),
  bank("magic", "Magic", "wizard witch spell wand potion charm crystal cauldron cloak rune scroll dragon tower apprentice mystery"),
  bank("wizards", "Wizards", "merlin gandalf oz dumbledore radagast saruman wizard staff robe spell tower book potion owl beard"),
  bank("heroes", "Heroes", "courage rescue quest shield sword cape justice strength honor battle friend leader hope victory legend"),
  bank("villains", "Villains", "scheme lair shadow mask power trap rival threat army secret revenge danger cunning defeat escape"),
  bank("royalty", "Royalty", "king queen prince princess duke duchess crown throne palace castle scepter jewel court guard heir reign"),
  bank("festivals", "Festivals", "carnival parade music dance costume lantern fireworks feast crowd stage drum color celebration street mask"),
  bank("holidays", "Holidays", "travel beach family hotel flight luggage photo relax journey resort summer winter cruise tour postcard"),
  bank("carnival", "Carnival", "parade float costume mask music drum dance confetti color crowd street ride ticket booth fun festival"),
  bank("circus", "Circus", "clown acrobat juggler trapeze ringmaster tent lion horse hoop rope cannon drum ticket crowd show"),
  bank("traditions", "Traditions", "custom ritual family feast dance song dress story craft holiday wedding greeting gift heritage culture"),
  bank("weddings", "Weddings", "bride groom ring dress suit veil bouquet cake dance music guest vow aisle flower toast photo"),
  bank("birthdays", "Birthdays", "cake candle gift party balloon card wish song friend family surprise game hat sweet celebrate"),
  bank("mythology", "Mythology", "god goddess hero monster titan oracle temple underworld heaven legend myth quest fate magic ancient"),
  bank("olympians", "Olympians", "zeus hera athena apollo artemis ares hermes demeter poseidon hades hephaestus hestia dionysus olympus"),
  bank("monsters", "Monsters", "dragon giant troll ogre goblin vampire werewolf zombie mummy ghost kraken hydra cyclops griffin beast"),
  bank("ghosts", "Ghosts", "spirit phantom specter shadow haunt eerie mansion grave mist whisper cold night candle attic mystery"),
  bank("treasure", "Treasure", "gold silver jewel pearl diamond ruby emerald coin chest map island cave pirate crown ancient hidden"),
  bank("mysteries", "Mysteries", "clue secret puzzle suspect detective alibi evidence shadow letter key lock code riddle solve hidden"),
  bank("detectives", "Detectives", "sherlock poirot marple clue case suspect witness alibi evidence magnify notebook mystery solve police trail"),
  bank("adventure", "Adventure", "journey quest map compass trail mountain jungle desert island cave river camp explore courage discovery"),
  bank("survival", "Survival", "shelter water fire food rope knife compass signal firstaid warmth rescue forest desert storm courage"),
  bank("trekking", "Trekking", "boots trail pack pole map compass ridge valley summit camp water jacket tent guide climb view"),
  bank("sailing", "Sailing", "sail mast boom hull rudder anchor rope knot deck cabin compass wind wave harbor skipper yacht"),
  bank("cruises", "Cruises", "ship cabin deck pool buffet port island ocean captain lounge show excursion sunset balcony voyage"),
  bank("railways", "Railways", "station platform track signal engine carriage ticket tunnel bridge conductor sleeper express freight journey"),
  bank("subways", "Subways", "metro station tunnel platform train map line ticket gate escalator commuter signal carriage underground"),
  bank("highways", "Highways", "road lane exit bridge tunnel sign traffic truck car ramp toll junction asphalt journey map"),
  bank("harbors", "Harbors", "dock pier quay ship boat ferry anchor crane cargo warehouse lighthouse channel tug sailor port"),
  bank("lighthouses", "Lighthouses", "beacon tower lamp coast cliff keeper lens flash foghorn storm sea rock ship warning night"),
  bank("villages", "Villages", "cottage church square market inn farm lane bridge school bakery garden well neighbor festival"),
  bank("skylines", "Skylines", "tower spire dome bridge rooftop city sunset lights glass steel horizon office crane landmark"),
  bank("neighborhoods", "Districts", "street avenue block park school market cafe shop library station homes garden square community"),
  bank("borders", "Borders", "boundary fence gate crossing passport customs map nation river mountain marker patrol bridge checkpoint"),
  bank("postcards", "Postcards", "picture stamp message address travel beach city mountain museum memory mail friend holiday view"),
  bank("basketball", "Basketball", "basket court hoop net ball dribble pass shoot dunk rebound guard center forward coach referee foul"),
  bank("baseball", "Baseball", "pitcher catcher batter diamond base inning homerun strike ball glove bat dugout umpire field team"),
  bank("tennis", "Tennis", "racket ball court net serve volley forehand backhand ace deuce set match player umpire baseline"),
  bank("cricket", "Cricket", "bat ball wicket bowler batter crease pitch run catch stump umpire over boundary spinner team"),
  bank("rugby", "Rugby", "ball try scrum ruck maul tackle pass kick post winger prop hooker referee pitch team"),
  bank("hockey", "Hockey", "puck stick rink goal goalie skate ice helmet pass shot check period referee team bench"),
  bank("volleyball", "Volleyball", "ball net serve spike block set dig court libero setter rotation referee beach team match"),
  bank("handball", "Handball", "ball court goal keeper throw pass dribble wing pivot defense attack referee team match"),
  bank("golf", "Golf", "club ball tee green fairway bunker hole putt drive iron wedge caddie flag golfer course"),
  bank("boxing", "Boxing", "glove ring punch jab hook uppercut guard round bell corner boxer referee canvas belt"),
  bank("wrestling", "Wrestling", "mat hold pin throw grapple takedown coach referee match weight stance escape point"),
  bank("fencing", "Fencing", "foil epee sabre mask blade guard lunge parry thrust piste point fencer bout referee"),
  bank("archery", "Archery", "bow arrow target quiver string nock shaft feather archer aim bullseye range score release"),
  bank("cycling", "Cycling", "bicycle pedal wheel chain gear brake saddle helmet road track rider race sprint climb"),
  bank("swimming", "Swimming", "pool lane water stroke freestyle breaststroke backstroke butterfly dive turn swimmer relay goggles"),
  bank("diving", "Diving", "board platform pool spring twist flip entry splash judge score diver height water"),
  bank("rowing", "Rowing", "boat oar crew shell coxswain stroke bow stern river lake race regatta seat"),
  bank("surfing", "Surfing", "board wave ocean beach swell tide reef surfer wax leash barrel break paddle"),
  bank("skiing", "Skiing", "ski pole slope snow lift lodge boot helmet slalom downhill jump racer mountain"),
  bank("skating", "Skating", "skate ice rink blade spin jump glide helmet figure hockey speed balance"),
  bank("climbing", "Climbing", "rope harness carabiner chalk hold wall cliff belay anchor helmet climber summit route"),
  bank("running", "Running", "shoe track runner sprint jog marathon relay lane pace finish start coach race"),
  bank("gymnastics", "Gymnastics", "beam bars vault floor rings pommel ribbon hoop tumble flip balance gymnast coach"),
  bank("martialarts", "Martialarts", "karate judo aikido kungfu taekwondo dojo belt kick punch block kata sensei spar"),
  bank("bowling", "Bowling", "ball pin lane strike spare gutter shoe alley frame score roll team"),
  bank("billiards", "Billiards", "cue ball table pocket chalk rack break shot angle rail player eightball"),
  bank("darts", "Darts", "dart board bullseye flight barrel point throw score double triple player match"),
  bank("chess", "Chess", "king queen rook bishop knight pawn board check mate castle gambit player clock"),
  bank("checkers", "Checkers", "board piece king jump move diagonal capture red black player turn crown"),
  bank("cards", "Cards", "ace king queen jack heart diamond club spade deck shuffle deal hand joker"),
  bank("olympics", "Olympics", "athlete medal torch podium stadium games gold silver bronze nation record ceremony"),
  bank("stadiums", "Stadiums", "wembley maracana campnou anfield san siro azteca olympic arena crowd pitch stand gate"),
  bank("footballers", "Footballers", "messi ronaldo pele maradona zidane cruyff beckham neymar mbappe haaland modric iniesta xavi kaka ronaldinho"),
  bank("tennisstars", "Tennisstars", "federer nadal djokovic serena venus graf borg laver murray agassi sampras henin osaka sinner"),
  bank("racers", "Racers", "senna schumacher hamilton prost vettel alonso verstappen lauda mansell clark fangio button rosberg"),
  bank("teams", "Teams", "arsenal chelsea liverpool everton barcelona juventus milan ajax benfica porto celtic dortmund bayern sevilla"),
  bank("trophies", "Trophies", "worldcup olympics wimbledon superbowl stanley ryder davis ashes masters league medal shield cup"),
  bank("coaching", "Coaching", "coach player tactic drill practice team whistle plan fitness strategy motivate bench match improve"),
  bank("fitness", "Fitness", "strength cardio balance stretch squat lunge plank pushup pullup run cycle swim gym trainer"),
  bank("yoga", "Yoga", "pose mat breath lotus cobra warrior tree bridge twist balance stretch calm focus"),
  bank("planets", "Planets", "mercury venus earth mars jupiter saturn uranus neptune orbit moon sun system rocky gas"),
  bank("moons", "Moons", "luna phobos deimos io europa ganymede callisto titan rhea enceladus triton charon orbit crater"),
  bank("stars", "Stars", "sirius vega rigel betelgeuse polaris altair arcturus aldebaran spica deneb sun light giant dwarf"),
  bank("galaxies", "Galaxies", "andromeda milkyway whirlpool sombrero pinwheel tadpole cartwheel spiral ellipse cluster stars dust"),
  bank("constellation", "StarSigns", "orion draco lyra cygnus aquila cassiopeia perseus phoenix hydra centaurus pegasus stars sky"),
  bank("spaceflight", "Spaceflight", "rocket capsule module launch orbit astronaut mission station shuttle booster landing space suit"),
  bank("rockets", "Rockets", "saturn falcon atlas delta soyuz ariane booster engine fuel nozzle stage launch orbit payload"),
  bank("astronauts", "Astronauts", "armstrong aldrin gagarin tereshkova glenn ride hadfield jemison kelly peake chaffee grissom"),
  bank("telescopes", "Telescopes", "hubble webb kepler spitzer chandra lens mirror scope mount focus light image observatory"),
  bank("robots", "Robots", "sensor motor circuit arm wheel camera code battery metal servo android drone machine automate"),
  bank("engineering", "Engineering", "design build test model bridge engine machine circuit structure material measure solve plan"),
  bank("mechanics", "Mechanics", "force motion speed mass energy work lever pulley gear spring friction torque balance"),
  bank("electricity", "Electricity", "current voltage charge circuit wire battery switch resistor power spark electron ampere"),
  bank("magnetism", "Magnetism", "magnet pole north south field iron attract repel compass coil force flux"),
  bank("optics", "Optics", "light lens mirror prism focus image laser color ray reflect refract glass spectrum"),
  bank("acoustics", "Acoustics", "sound wave echo pitch tone volume frequency rhythm noise speaker ear vibration"),
  bank("atoms", "Atoms", "proton neutron electron nucleus orbit shell element isotope ion charge particle bond"),
  bank("elements", "Elements", "hydrogen helium carbon oxygen nitrogen neon sodium iron copper silver gold zinc tin lead"),
  bank("laboratory", "Laboratory", "beaker flask tube burner pipette sample microscope scale glove coat test liquid measure"),
  bank("experiments", "Experiments", "question theory test sample control result data measure observe record repeat prove"),
  bank("genetics", "Genetics", "gene dna rna genome trait cell chromosome allele inherit mutation helix code"),
  bank("cells", "Cells", "nucleus membrane cytoplasm protein organelle divide tissue energy ribosome vacuole mitochondria"),
  bank("microbes", "Microbes", "bacteria virus fungus yeast algae protozoa cell culture colony spore microscope tiny"),
  bank("bacteria", "Bacteria", "bacillus coccus spirillum colony culture microbe cell divide flagella yogurt soil gut"),
  bank("viruses", "Viruses", "capsid genome host infect spread immune vaccine cell strain particle protein replicate"),
  bank("evolution", "Evolution", "species fossil trait adapt change ancestor natural select survive variation gene time"),
  bank("brain", "Brain", "neuron cortex cerebellum memory thought nerve signal lobe skull mind learn dream"),
  bank("senses", "Senses", "sight sound smell taste touch eye ear nose tongue skin signal brain"),
  bank("skeleton", "Skeleton", "skull spine rib pelvis femur tibia fibula humerus radius ulna joint bone"),
  bank("muscles", "Muscles", "biceps triceps tendon fiber strength contract relax heart calf thigh shoulder movement"),
  bank("heart", "Heart", "pulse blood artery vein chamber valve beat oxygen chest muscle rhythm health"),
  bank("nutrition", "Nutrition", "protein vitamin mineral fiber water energy calorie fruit grain dairy balance health"),
  bank("health", "Health", "sleep water exercise food hygiene doctor checkup medicine rest wellness habit"),
  bank("firstaid", "Firstaid", "bandage gauze plaster antiseptic wound burn splint ice glove kit help emergency"),
  bank("geometry", "Geometry", "circle square triangle rectangle polygon angle line point curve radius diameter area"),
  bank("numbers", "Numbers", "zero one two three four five six seven eight nine ten hundred"),
  bank("algebra", "Algebra", "variable equation formula solve value term factor graph function plus minus equal"),
  bank("statistics", "Statistics", "data mean median mode range chart sample survey average percent result"),
  bank("coding", "Coding", "code function variable string number array object loop class bug test build"),
  bank("internet", "Internet", "website browser server client network router domain link page search cloud"),
  bank("webdesign", "Webdesign", "layout color font button image menu grid page mobile style icon"),
  bank("software", "Software", "program app code file data update install system user tool version"),
  bank("hardware", "Hardware", "screen keyboard mouse chip board cable drive memory port speaker camera"),
  bank("networks", "Networks", "router switch cable wifi signal packet server client address port firewall"),
  bank("security", "Security", "password cipher key lock firewall backup update privacy login token safe"),
  bank("databases", "Databases", "table row column query index record field key data server schema"),
  bank("gaming", "Gaming", "player level score quest boss map item skill team match console save"),
  bank("games", "Games", "minecraft fortnite tetris portal zelda mario sonic pacman celeste doom halo fifa"),
  bank("boardgames", "Boardgames", "monopoly scrabble catan risk chess clue sorry dominoes ticket carrom ludo"),
  bank("puzzles", "Puzzles", "sudoku crossword jigsaw riddle maze rebus logic clue piece solve brain"),
  bank("consoles", "Consoles", "playstation xbox switch genesis dreamcast gamecube wii atari console pad cartridge"),
  bank("phototech", "Cameras", "camera lens shutter sensor flash tripod focus zoom aperture photo film frame"),
  bank("phones", "Phones", "mobile screen call text camera battery charger signal app contact speaker"),
  bank("clocks", "Clocks", "hour minute second hand face alarm tick pendulum digital noon midnight time"),
  bank("watches", "Watches", "strap dial crown hand quartz smart timer buckle wrist face second"),
  bank("furniture", "Furniture", "chair table sofa bed desk shelf stool bench cabinet drawer wardrobe dresser"),
  bank("bedroom", "Bedroom", "bed pillow blanket sheet wardrobe dresser lamp mirror rug curtain nightstand"),
  bank("bathroom", "Bathroom", "bath shower sink tap mirror towel soap brush comb toilet mat sponge"),
  bank("office", "Office", "desk chair computer phone printer paper pen folder cabinet meeting calendar"),
  bank("school", "School", "teacher student class desk book pen pencil board lesson test bell library"),
  bank("classroom", "Classroom", "desk chair board chalk marker book teacher pupil lesson clock map poster"),
  bank("stationery", "Stationery", "pencil pen eraser ruler marker crayon paper notebook folder clip stapler"),
  bank("workshop", "Workshop", "bench hammer saw drill clamp vise wood metal tool screw nail measure"),
  bank("garage", "Garage", "car tool tire jack oil shelf door engine bike box ladder workbench"),
  bank("laundry", "Laundry", "washer dryer soap basket shirt sock towel fold iron stain clean"),
  bank("cleaning", "Cleaning", "broom mop vacuum brush cloth soap bucket sponge spray dust polish"),
  bank("containers", "Containers", "box jar bottle can basket bag crate barrel bin case pouch tin"),
  bank("fasteners", "Fasteners", "nail screw bolt nut washer rivet pin clip hook staple buckle zip"),
  bank("materials", "Materials", "wood metal glass plastic paper cotton wool silk leather stone clay"),
  bank("metals", "Metals", "iron copper silver gold zinc tin lead nickel chrome steel brass bronze"),
  bank("woodwork", "Woodwork", "timber plank saw chisel plane hammer nail glue joint bench carve sand"),
  bank("pottery", "Pottery", "clay wheel kiln glaze pot bowl vase mug plate sculpt fire shape"),
  bank("sewing", "Sewing", "needle thread fabric stitch button zipper pattern scissors pin hem seam"),
  bank("knitting", "Knitting", "yarn wool needle stitch loop scarf sweater sock pattern purl knit"),
  bank("origami", "Origami", "paper fold crane flower boat frog star wing crease square art"),
  bank("toys", "Toys", "doll ball block puzzle kite train robot teddy yoyo marble hoop puppet"),
  bank("kites", "Kites", "kite string tail wind sky reel paper frame fly beach color"),
  bank("balloons", "Balloons", "balloon air helium string party color float pop basket flight"),
  bank("keys", "Keys", "key lock door car piano board metal ring spare turn open code"),
  bank("doors", "Doors", "door handle hinge lock key frame panel knob gate entry open"),
  bank("windows", "Windows", "glass frame pane curtain sill shutter view light open screen"),
  bank("singers", "Singers", "adele beyonce madonna shakira rihanna cher pink sia enya lorde usher drake prince sting bowie"),
  bank("bands", "Bands", "beatles queen abba nirvana oasis muse coldplay blur genesis rush kiss rem doors eagles radiohead"),
  bank("rockmusic", "Rock", "guitar drums bass singer band stage concert riff solo amp loud rhythm album tour fan"),
  bank("jazz", "Jazz", "saxophone trumpet piano bass drums swing bebop blues club solo rhythm improv melody band"),
  bank("blues", "Blues", "guitar harmonica singer rhythm bass shuffle delta chicago soul song twelvebar slide stage"),
  bank("popmusic", "Pop", "singer chorus melody dance radio chart single album stage fan video catchy beat star"),
  bank("opera", "Opera", "soprano tenor baritone aria chorus orchestra stage costume drama libretto composer theater voice"),
  bank("ballet", "Ballet", "dancer pointe tutu stage barre leap turn music costume grace studio company shoe"),
  bank("dance", "Dance", "salsa tango waltz samba ballet tap disco swing rumba mambo hiphop step rhythm music"),
  bank("guitar", "Guitar", "string fret neck body pick chord bridge tuner acoustic electric amp strum riff solo"),
  bank("piano", "Piano", "key pedal chord scale melody grand upright bench player octave note song concert"),
  bank("drums", "Drums", "snare bass tom cymbal stick beat rhythm pedal kit roll crash drummer stage"),
  bank("concerts", "Concerts", "stage singer band crowd ticket venue light sound speaker song encore tour fan"),
  bank("albums", "Albums", "record vinyl cover track song artist studio release chart sleeve music classic"),
  bank("actors", "Actors", "hanks cruise deniro pacino dicaprio pitt clooney freeman hopkins bale grant poitier bogart cage"),
  bank("actresses", "Actresses", "streep hepburn garbo foster winslet kidman bullock berry stone blunt roberts davis dench"),
  bank("directors", "Directors", "spielberg kubrick scorsese coppola hitchcock cameron nolan burton lee allen lynch ford kurosawa"),
  bank("movies", "Movies", "jaws rocky alien avatar frozen shrek psycho gravity gladiator titanic inception casablanca vertigo"),
  bank("comedy", "Comedy", "joke laugh comic sketch satire humor punchline clown sitcom stage smile fun audience"),
  bank("animation", "Animation", "frame drawing motion cartoon studio artist model voice color story character screen"),
  bank("cartoons", "Cartoons", "snoopy garfield scooby popeye tintin asterix smurfs simpsons flintstone jetsons calvin hobbes"),
  bank("superheroes", "Superheroes", "superman batman spiderman hulk thor flash aquaman ironman antman daredevil storm blade"),
  bank("comics", "Comics", "panel speech hero villain artist ink page issue story bubble cover strip reader"),
  bank("fantasy", "Fantasy", "wizard dragon castle sword magic elf dwarf quest kingdom forest spell hero"),
  bank("sciencefiction", "Scifi", "robot alien planet rocket future space laser android galaxy ship clone time"),
  bank("thrillers", "Thrillers", "mystery danger chase secret spy crime suspect escape twist shadow tension clue"),
  bank("westerns", "Westerns", "cowboy horse sheriff desert saloon outlaw ranch rodeo train pistol town"),
  bank("documentary", "Documentary", "camera truth nature history interview archive narrator film story fact research"),
  bank("novels", "Novels", "story chapter author reader plot hero setting cover page fiction ending library"),
  bank("poetry", "Poetry", "poem verse rhyme rhythm stanza poet line meter image word sonnet"),
  bank("bookgenres", "Genres", "mystery fantasy romance history horror thriller western scifi poetry drama comedy memoir"),
  bank("libraries", "Libraries", "book shelf reader catalog archive desk card quiet study librarian return loan"),
  bank("printing", "Printing", "press ink paper type page plate roller book poster font color print"),
  bank("newspapers", "Newspapers", "headline article editor reporter photo press daily column page news print reader"),
  bank("magazines", "Magazines", "cover article photo editor issue page feature fashion news reader monthly"),
  bank("supercars", "Supercars", "ferrari porsche lamborghini bugatti mclaren pagani koenigsegg maserati lotus aston corvette viper"),
  bank("classiccars", "Classics", "mustang beetle mini cobra jaguar cadillac charger camaro impala pinto corvette thunderbird"),
  bank("trucks", "Trucks", "pickup lorry tanker trailer cab wheel cargo diesel freight dump tow flatbed"),
  bank("electriccars", "Electriccars", "tesla rivian lucid leaf bolt taycan polestar battery motor charge range cable"),
  bank("racingcars", "Racecars", "formula indy rally nascar kart lotus ferrari mclaren engine tire wing speed track"),
  bank("carmodels", "Carmodels", "civic corolla mustang camaro beetle golf focus fiesta accord prius polo clio"),
  bank("sneakers", "Sneakers", "nike adidas puma reebok converse vans asics fila jordan newbalance shoe lace sole"),
  bank("cosmetics", "Cosmetics", "lipstick mascara powder blush liner gloss cream brush mirror color makeup bottle"),
  bank("hairstyles", "Hairstyles", "bob braid ponytail bun fringe curls waves crop fade mohawk pixie afro"),
  bank("jewelry", "Jewelry", "ring necklace bracelet earring brooch pendant chain pearl diamond gold silver jewel"),
  bank("handbags", "Handbags", "tote clutch satchel purse backpack pouch strap buckle leather pocket zipper"),
  bank("shopping", "Shopping", "store cart basket price sale cash card receipt shopper shelf bag market"),
  bank("business", "Business", "company office manager staff client sale product market profit meeting plan team"),
  bank("banking", "Banking", "account money card cash loan credit debit branch teller vault interest save"),
  bank("money", "Money", "coin note cash wallet bank price cost value dollar euro pound yen"),
  bank("economy", "Economy", "trade market price wage job growth tax budget money export import industry"),
  bank("builders", "Builders", "brick cement wall roof hammer drill ladder plan helmet beam site worker"),
  bank("doctors", "Doctors", "clinic patient nurse health exam chart medicine stethoscope ward care surgeon"),
  bank("teachers", "Teachers", "class lesson pupil school book board grade test learn explain homework"),
  bank("chefs", "Chefs", "kitchen knife pan oven recipe sauce taste cook plate apron meal"),
  bank("bakers", "Bakers", "bread flour dough yeast oven loaf cake pastry sugar butter tray"),
  bank("firefighters", "Firefighters", "fire hose ladder truck helmet rescue station alarm smoke water crew"),
  bank("police", "Police", "officer badge patrol station radio car law arrest siren uniform detective"),
  bank("pilots", "Pilots", "cockpit plane runway tower flight wing engine radar route captain sky"),
  bank("sailors", "Sailors", "ship deck sail rope anchor ocean captain crew mast harbor compass"),
  bank("colors", "Colors", "red blue green yellow orange purple pink brown black white gray cyan"),
  bank("shapes", "Shapes", "circle square triangle oval cube sphere cone star heart diamond rectangle"),
  bank("textures", "Textures", "smooth rough soft hard silky fuzzy bumpy grainy sticky glossy matte"),
  bank("patterns", "Patterns", "stripe dot check plaid floral spiral wave zigzag grid spot repeat"),
  bank("emotions", "Emotions", "happy sad angry calm proud shy brave lonely excited worried surprised"),
  bank("personality", "Personality", "kind funny honest loyal patient clever gentle brave calm curious friendly"),
  bank("friendship", "Friendship", "friend trust laugh share help listen loyal kind support memory together"),
  bank("family", "Family", "mother father sister brother aunt uncle cousin baby parent child grandpa"),
  bank("childhood", "Childhood", "play toy school friend game park story bike candy dream family"),
  bank("weekends", "Weekends", "sleep brunch park movie friend family walk game relax trip cafe"),
  bank("hobbies", "Hobbies", "reading gaming painting hiking fishing cooking sewing gardening music cycling"),
  bank("gardening", "Gardening", "soil seed flower pot water spade rake glove compost weed plant"),
  bank("fishing", "Fishing", "rod reel line hook bait boat lake river fish net catch"),
  bank("picnics", "Picnics", "basket blanket park sandwich fruit drink plate grass sun family"),
  bank("parties", "Parties", "music dance cake guest drink snack balloon game gift laugh"),
  bank("relaxation", "Relaxation", "calm quiet rest sleep bath music book candle tea hammock breathe"),
  bank("memories", "Memories", "photo story family friend travel school holiday smile moment past"),
  bank("dreams", "Dreams", "sleep night cloud fly wonder strange story moon wish imagine wake"),
  bank("luck", "Luck", "clover horseshoe charm wish fortune chance dice coin star lucky"),
  bank("symbols", "Symbols", "heart star arrow cross circle peace crown key eye moon sun"),
  bank("alphabet", "Alphabet", "letter vowel word sound write read spell script font line page"),
  bank("grammar", "Grammar", "noun verb adjective adverb sentence clause tense plural phrase word"),
  bank("languageskills", "Vocabulary", "word meaning spell speak listen read write phrase learn dictionary"),
  bank("questions", "Questions", "who what where when why how answer ask wonder solve explain"),
  bank("knowledge", "Knowledge", "learn study fact idea book school teacher memory skill wisdom"),
]);
